apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  ports:
    - name: loadbalancer-port
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer
