apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
    - name: vproapp-port
      port: 8090
      nodePort: 30001
      targetPort: 8080
      protocol: TCP
  selector:
    app: vproapp
  type: NodePort
